name: stormbird
description: Every message. One place.

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/stormbird-msg/desktop

version: 0.1.0+1

environment:
  sdk: ^3.12.2
  flutter: ^3.44.5

dependencies:
  flutter:
    sdk: flutter

  yaraui:
    git:
      ref: main
      url: https://github.com/softyesti/yaraui
  webview_cef:
    git:
      ref: main
      url: https://github.com/softyesti/webview_cef

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.3.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: false
